[package]
name = "paws_ui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]
doctest = false
test = false

[dependencies]
arkit.workspace = true
base64.workspace = true
dioxus.workspace = true
paws_core.workspace = true
paws_model.workspace = true
napi-derive-ohos.workspace = true
napi-ohos.workspace = true
ohos-fileuri-binding = { path = "../../../../ohos-rs/ohos-native-bindings/crates/fileuri" }
ohos-fileshare-binding = { path = "../../../../ohos-rs/ohos-native-bindings/crates/fileshare" }
ohos-resource-manager-binding = { path = "../../../../ohos-rs/ohos-native-bindings/crates/resource_manager" }
openharmony-ability-plugin-files.workspace = true
openharmony-ability-plugin-url.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
time.workspace = true
tokio.workspace = true
url.workspace = true

[build-dependencies]
napi-build-ohos.workspace = true
