/* auto-generated by OHOS-RS */
/* eslint-disable */

export declare function activateProfile(profileId: string): Promise<void>

export declare function closeConnection(id: string): void

export declare function closeAllConnections(): void

export declare function clearLogs(): void

export declare function clearRequestHistory(): void

export declare function configureAppHome(homeDir: string): void

export declare function configureSystemColorMode(colorMode: number): void

export declare function configureUiLocale(locale: string): void

export declare function defaultVpnOptions(): string

export declare function deleteProfile(profileId: string): Promise<void>

export declare function deleteRule(ruleId: string): void

export declare function destroy(): void

export declare function importProfileFromContent(name: string, source: string, rawYaml: string): Promise<string>

export declare function importProfileFromPicker(): Promise<string>

export declare function importProfileFromUrl(url: string, name?: string | undefined | null): Promise<string>

export declare function importRulesFromContent(profileId: string | undefined | null, source: string, rulesText: string): string

export declare function init(context?: AbilityInitContext): ApplicationLifecycle

export declare function onBackPressIntercept(): boolean

export declare function querySnapshot(): string

export declare function refreshProfile(profileId: string): Promise<void>

export declare function refreshProvider(providerName: string): Promise<void>

export declare function refreshProviderOfType(providerType: string, providerName: string): Promise<void>

export declare function refreshAllProviders(): Promise<void>

export declare function refreshDueProfiles(): Promise<void>

export declare function registerPlatformCallbacks(callbacks: object): void

export declare function reloadConfig(profileId: string): Promise<void>

export declare function render(helper: object, slot: NodeContent): void

export declare function reorderRules(profileId: string, orderedRuleIdsJson: string): void

export declare function refreshAllProfiles(): Promise<void>

export declare function selectProxy(group: string, proxy: string): Promise<void>

export declare function unfixProxy(group: string): Promise<void>

export declare function seedGeodataFromRawfiles(resourceManager: resourceManager.ResourceManager): number

export declare function setMode(mode: string): Promise<void>

export declare function setPlatformNetworkProtected(protected: boolean, error?: string | undefined | null): void

export declare function setPlatformVpnRunning(running: boolean): void
export declare function setPlatformVpnStarting(starting: boolean): void
export declare function expirePlatformVpnStart(): boolean
export declare function setPlatformVpnFailed(error: string): void

export declare function profileRawYaml(profileId: string): string

export declare function prepareVpn(): Promise<boolean>

export declare function restoreProfileBackup(profileId: string): Promise<void>

export declare function setProfileDnsServers(profileId: string, dnsServersJson: string): Promise<void>

export declare function setProfileDnsConfig(profileId: string, dnsServersJson: string, dnsFallbacksJson: string, dnsNameserverPolicyJson: string): Promise<void>

export declare function setProfileVpnConfig(profileId: string, systemProxy: boolean, dnsHijacking: boolean, allowBypass: boolean, stack: string): Promise<void>

export declare function setRuleEnabled(profileId: string, ruleId: string, enabled: boolean): void

export declare function startVpn(fd: number, optionsJson: string): Promise<void>

export declare function stopVpn(): Promise<void>

export declare function persistVpnTelemetry(): void

export declare function testProxyDelay(proxyName: string, url?: string | undefined | null, timeoutMs?: number | undefined | null): Promise<number>

export declare function testProxyEcho(proxyName: string, url: string, payload: string, timeoutMs?: number | undefined | null): Promise<string>

export declare function updateProfileContent(profileId: string, rawYaml: string): Promise<void>
export declare function updateProfileSubscription(profileId: string, name: string, subscriptionUrl: string): void

export declare function validateProfileContent(rawYaml: string): Promise<void>

export interface AbilityInitContext {
  basePath?: string
  prefPath?: string
  preferredLocales?: string
  moduleName?: string
}

export interface ApplicationLifecycle {
  environmentCallback: EnvironmentCallback
  windowStageEventCallback: WindowStageEventCallback
  keyboardEventCallback: KeyboardCallback
}

export interface DownloadStartResult {
  allow: boolean
  tempPath?: string
}

export interface EnvironmentCallback {
  onConfigurationUpdated: () => void
  onMemoryLevel: (arg: number) => void
}

export interface KeyboardCallback {
  onKeyboardHeightChange: (arg: number) => void
}

export interface WebViewInitData {
  url?: string
  id?: string
  style?: WebViewStyle
  javascriptEnabled?: boolean
  devtools?: boolean
  userAgent?: string
  autoplay?: boolean
  initializationScripts?: Array<string>
  headers?: Record<string, string>
  html?: string
  transparent?: boolean
  onDragAndDrop?: (arg: string) => void
  onDownloadStart: OnDownloadStart
  onDownloadEnd: OnDownloadEnd
  onNavigationRequest?: (arg: string) => boolean
  onTitleChange?: (arg: string) => void
}

export interface WebViewStyle {
  x?: number | string
  y?: number | string
  visible?: boolean
  backgroundColor?: string
}

export interface WindowStageEventCallback {
  onWindowStageCreate: () => void
  onWindowStageDestroy: () => void
  onAbilityCreate: () => void
  onAbilityDestroy: () => void
  onAbilitySaveState: () => void
  onAbilityRestoreState: () => void
  onWindowStageEvent: (arg: number) => void
  onWindowSizeChange: (arg: object) => void
  onWindowRectChange: (arg: object) => void
  onAvoidAreaChange: (arg: object) => void
}
