/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface UrlOpenRequest {
  url: string
}

export interface UrlOpenResponse {
  accepted: boolean
}

/**
  * One suffix filter group: a display name plus `;`-separated suffixes (e.g. `"md"`).
  * The pattern stays structured; the ArkTS plugin converts it to the picker grammar.
  */
export interface FileDialogFilter {
  name?: string
  pattern?: string
}

export interface FileDialogOptions {
  /** One of [`dialog_type`] constants. */
  dialogType: string
  allowMany: boolean
  defaultLocation?: string
  filters: Array<FileDialogFilter>
}

export interface FileDialogResponse {
  /** Selected file URIs. */
  files: Array<string>
  /** Selected filter index, or -1 when the platform does not report one. */
  filter: number
}

export interface ClipboardSetRequest {
  text: string
}

export interface ClipboardSetResponse {

}

export interface ColorModeRequest {
  /** `ConfigurationConstant.ColorMode` value pushed from native UI. */
  mode: number
}

export interface ColorModeResponse {

}

export interface ExportTextRequest {
  /**
    * `"profile"` or `"log"`; selects the fallback name, extension and
    * suffix choices on the ArkTS side.
    */
  exportKind: string
  suggestedName: string
  content: string
}

export interface ExportTextResponse {

}

export interface ScanRequest {

}

export interface ScanResponse {
  /** Trimmed scan payload; empty when the user cancelled the scan dialog. */
  content: string
}

export interface VpnStartRequest {
  /** Serialized `VpnOptions` JSON for the extension Want. */
  optionsJson: string
}

export interface VpnStartResponse {

}

export interface VpnStopRequest {

}

export interface VpnStopResponse {

}

export declare function activateProfile(profileId: string): Promise<void>

export declare function attachPlatformSharedMemory(ashmemFd: number, notificationFd: number): void

export declare function awaitPlatformVpnStart(attemptId: string): Promise<string>

export declare function awaitPlatformVpnStartAttachment(attemptId: string, timeoutMs: number): Promise<boolean>

export declare function beginPlatformVpnStart(): string

export declare function bindPlatformVpnStart(attemptId: string): void

export declare function cancelPlatformVpnStart(attemptId: string): boolean

export declare function clearLogs(): void

export declare function clearRequestHistory(): void

export declare function closeAllConnections(): void

export declare function closeConnection(id: string): void

export declare function configureAppHome(homeDir: string): void

export declare function configureSystemColorMode(colorMode: number): void

export declare function configureUiLocale(locale: string): void

export declare function defaultVpnOptions(): string

export declare function deleteProfile(profileId: string): Promise<void>

export declare function deleteRule(ruleId: string): void

export declare function destroy(): void

export declare function expirePlatformVpnStart(): boolean

export declare function failPlatformVpnStart(attemptId: string, error: string): boolean

export declare function failUnattachedPlatformVpnStart(attemptId: string, error: string): boolean

export declare function importProfileFromContent(name: string, source: string, rawYaml: string): Promise<string>

export declare function importProfileFromPicker(): Promise<string>

export declare function importProfileFromUrl(url: string, name?: string | undefined | null): Promise<string>

export declare function importRulesFromContent(profileId: string | undefined | null, source: string, rulesText: string): string

export declare function init(context?: AbilityInitContext): ApplicationLifecycle

export declare function initializePlatformSharedMemory(): string

export declare function onBackPressIntercept(): boolean

/** ArkTS-only lifecycle transitions, currently UI-context readiness. */
export declare function onBridgeLifecycle(kind: string): void

/** Synchronous ArkTS platform callback -> Rust plugin decision port. */
export declare function onBridgeSyncEvent(pluginId: string, event: string, requestTypeName: string, responseTypeName: string, value: unknown): unknown

export declare function persistVpnTelemetry(): void

export declare function prepareVpn(): Promise<boolean>

export declare function profileRawYaml(profileId: string): string

export declare function querySnapshot(): string

export declare function refreshAllProfiles(): Promise<void>

export declare function refreshAllProviders(): Promise<void>

export declare function refreshDueProfiles(): Promise<void>

export declare function refreshProfile(profileId: string): Promise<void>

export declare function refreshProvider(providerName: string): Promise<void>

export declare function refreshProviderOfType(providerType: string, providerName: string): Promise<void>

export declare function reloadConfig(profileId: string): Promise<void>

export declare function render(bindings: object, slot: NodeContent): void

export declare function reorderRules(profileId: string, orderedRuleIdsJson: string): void

export declare function restoreProfileBackup(profileId: string): Promise<void>

export declare function seedGeodataFromRawfiles(resourceManager: resourceManager.ResourceManager): number

export declare function selectProxy(group: string, proxy: string): Promise<void>

export declare function setMode(mode: string): Promise<void>

export declare function setPlatformNetworkProtected(protected: boolean, error?: string | undefined | null): void

export declare function setPlatformVpnFailed(error: string): void

export declare function setPlatformVpnRunning(running: boolean): void

export declare function setPlatformVpnStarting(starting: boolean): void

export declare function setProfileDnsConfig(profileId: string, dnsServersJson: string, dnsFallbacksJson: string, dnsNameserverPolicyJson: string): Promise<void>

export declare function setProfileDnsServers(profileId: string, dnsServersJson: string): Promise<void>

export declare function setProfileVpnConfig(profileId: string, systemProxy: boolean, dnsHijacking: boolean, allowBypass: boolean, stack: string): Promise<void>

export declare function setRuleEnabled(profileId: string, ruleId: string, enabled: boolean): void

export declare function startVpn(fd: number, optionsJson: string): Promise<void>

export declare function stopVpn(): Promise<void>

export declare function syncPlatformChanges(): void

export declare function testProxyDelay(proxyName: string, url?: string | undefined | null, timeoutMs?: number | undefined | null): Promise<number>

export declare function testProxyEcho(proxyName: string, url: string, payload: string, timeoutMs?: number | undefined | null): Promise<string>

export declare function unfixProxy(group: string): Promise<void>

export declare function updateProfileContent(profileId: string, rawYaml: string): Promise<void>

export declare function updateProfileSubscription(profileId: string, name: string, subscriptionUrl: string): void

export declare function validateProfileContent(rawYaml: string): Promise<void>

export declare function waitForPlatformChange(timeoutMs: number): Promise<boolean>

export interface AbilityInitContext {
  basePath?: string
  prefPath?: string
  preferredLocales?: string
  moduleName?: string
}

export interface ApplicationLifecycle {
  environmentCallback: EnvironmentCallback
  windowStageEventCallback: WindowStageEventCallback
  keyboardEventCallback: KeyboardCallback
}

export interface EnvironmentCallback {
  onConfigurationUpdated: () => void
  onMemoryLevel: (arg: number) => void
}

export interface KeyboardCallback {
  onKeyboardHeightChange: (arg: number) => void
}

export interface NodeAcknowledgement {
  accepted: boolean
}

/** Appends the node of `child_handle` under the node of `parent_handle`. */
export interface NodeAppendChildRequest {
  parentHandle: number
  childHandle: number
  /** Window surface key; defaults to `"main"`. Parent and child must share the same window. */
  windowKey?: string
}

/** Window-scoped request marker for `create-container`: the response carries the new handle. */
export interface NodeCreateContainerRequest {
  /** Window surface key; defaults to `"main"`. */
  windowKey?: string
}

/** Detaches a handle-owned node from its parent and disposes it. */
export interface NodeDisposeRequest {
  handle: number
  /** Window surface key; defaults to `"main"`. */
  windowKey?: string
}

/** Opaque handle of a container `FrameNode` created in ArkTS. */
export interface NodeHandleResponse {
  handle: number
}

/** Appends a handle-owned node to the window root. */
export interface NodeMountIntoRootRequest {
  handle: number
  /** Window surface key; defaults to `"main"`. */
  windowKey?: string
}

export interface WindowStageEventCallback {
  onWindowStageCreate: () => void
  onWindowStageDestroy: () => void
  onAbilityCreate: (arg: string) => void
  onAbilityDestroy: () => void
  onAbilitySaveState: () => void
  onAbilityRestoreState: () => void
  onWindowStageEvent: (arg: number) => void
  onWindowSizeChange: (arg: object) => void
  onWindowRectChange: (arg: object) => void
  onAvoidAreaChange: (arg: object) => void
}

